name: tofu

# Controls when the action will run.
on: [push]

jobs:
  tofu-run:
    name: Setup OpenTofu
    runs-on: ubuntu-latest
    env:
      VERSION: "v1.7.0-alpha1"
      RELEASE: "tofu_1.7.0-alpha1_linux_amd64.tar.gz"
      PASSPHRASE: ${{secrets.encryptionPassphrase}}
      TFSTATE: ${{secrets.TFSTATE}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -OL https://github.com/opentofu/opentofu/releases/download/${VERSION}/${RELEASE}
          tar zxvf ${RELEASE}
      - run: |
          ./tofu init -backend-config="password=$(echo $TFSTATE)"
          ./tofu plan
          ./tofu apply -auto-approve
      - name: Run tmate if failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
