name: tofu

# Controls when the action will run.
on: [push]

jobs:
  tofu-run:
    name: Setup OpenTofu
    runs-on: ubuntu-latest
    env:
      VERSION: "v1.7.0-alpha1"
      RELEASE: "tofu_1.7.0-alpha1_linux_amd64.tar.gz"
      PASSPHRASE: ${{secrets.encryptionPassphrase}}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set the TF_ENCRYPTION env var, since it's multiline & uses a secret
        run: |
          TF_ENCRYPTION=$(echo "terraform {
            backend \"local\" {}
            encryption {
              key_provider \"pbkdf2\" \"my_passphrase\" {
                passphrase = ${{ env.PASSPHRASE }}
              }
              method \"aes_gcm\" \"my_method\" {
                keys = key_provider.pbkdf2.my_passphrase
              }
              state {
                method = method.aes_gcm.my_method
              }
            }
          }")
      - run: |
          curl -OL https://github.com/opentofu/opentofu/releases/download/${VERSION}/${RELEASE}
          tar zxvf ${RELEASE}
      - run: |
          ls -l
          ./tofu init
          ./tofu plan
          ./tofu apply -auto-approve
          cat terraform.tfstate
      - name: Run tmate if failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
